defmodule ReqLLM.ProviderCase do
  @moduledoc """
  Case template for provider-level testing.

  Provides a consistent test environment and common setup for testing
  ReqLLM provider implementations at the low-level Req plugin API level.

  ## Usage

      defmodule ReqLLM.Providers.MyProviderTest do
        use ReqLLM.ProviderCase, provider: ReqLLM.Providers.MyProvider
      end

  ## Automatic Setup

  - Sets appropriate API key environment variables
  - Imports helper functions for fixtures and assertions
  """

  use ExUnit.CaseTemplate

  import ExUnit.Assertions

  alias ReqLLM.Context

  using(opts) do
    provider = Keyword.get(opts, :provider)

    quote do
      use ExUnit.Case, async: false

      import ReqLLM.ProviderCase

      @provider unquote(provider)

      setup do
        if @provider do
          env_key = ReqLLM.ProviderCase.env_key_for(@provider)
          System.put_env(env_key, "test-key-12345")
        end

        :ok
      end
    end
  end

  @doc """
  Generates focused tests for a module implementing the public provider contract.

  The contract can verify the helpers and default callbacks generated by
  `use ReqLLM.Provider` in addition to the required behaviour callbacks.
  """
  defmacro provider_contract(opts) do
    provider = Keyword.fetch!(opts, :provider)
    provider_id = Keyword.fetch!(opts, :provider_id)
    default_base_url = Keyword.fetch!(opts, :default_base_url)
    provider_options = Keyword.get(opts, :provider_options, [])
    defaults? = Keyword.get(opts, :defaults, false)

    quote do
      @contract_provider unquote(provider)
      @contract_provider_id unquote(provider_id)
      @contract_default_base_url unquote(default_base_url)
      @contract_provider_options unquote(provider_options)

      @tag contract: :provider_extension
      test "provider contract declares the behaviour and required callbacks" do
        behaviours = @contract_provider.__info__(:attributes)[:behaviour] || []
        assert ReqLLM.Provider in behaviours

        missing_callbacks =
          ReqLLM.ProviderCase.required_provider_callbacks()
          |> Enum.reject(fn {name, arity} ->
            function_exported?(@contract_provider, name, arity)
          end)

        assert missing_callbacks == [],
               "missing required ReqLLM.Provider callbacks: #{inspect(missing_callbacks)}"
      end

      @tag contract: :provider_extension
      test "provider contract registers and routes inline models" do
        on_exit(fn -> ReqLLM.Providers.unregister(@contract_provider_id) end)

        assert {:ok, @contract_provider_id} = ReqLLM.Providers.register(@contract_provider)
        assert {:ok, @contract_provider} = ReqLLM.provider(@contract_provider_id)

        assert {:ok,
                %LLMDB.Model{
                  provider: @contract_provider_id,
                  id: "external-model",
                  provider_model_id: "external-model"
                }} =
                 ReqLLM.model(%{provider: @contract_provider_id, id: "external-model"})
      end

      @tag contract: :provider_extension
      test "provider contract exposes generated identity and schema helpers" do
        assert @contract_provider.provider_id() == @contract_provider_id
        assert @contract_provider.default_base_url() == @contract_default_base_url
        assert @contract_provider.base_url() == @contract_default_base_url

        assert %NimbleOptions{} = provider_schema = @contract_provider.provider_schema()
        assert Keyword.keys(provider_schema.schema) == @contract_provider_options
        assert @contract_provider.supported_provider_options() == @contract_provider_options

        assert %NimbleOptions{} =
                 extended =
                 @contract_provider.provider_extended_generation_schema()

        expected_keys =
          ReqLLM.Provider.Options.generation_schema().schema
          |> Keyword.keys()
          |> Kernel.++(@contract_provider_options)
          |> Enum.uniq()

        missing_keys = expected_keys -- Keyword.keys(extended.schema)

        assert missing_keys == [],
               "extended provider schema is missing keys: #{inspect(missing_keys)}"
      end

      unquote(
        if defaults? do
          quote do
            @tag contract: :provider_extension
            test "provider contract inherits documented default callback behavior" do
              default_callbacks = [
                prepare_request: 4,
                attach: 3,
                build_body: 1,
                encode_body: 1,
                decode_response: 1,
                extract_usage: 2,
                translate_options: 3,
                decode_stream_event: 2,
                attach_stream: 4
              ]

              missing_callbacks =
                Enum.reject(default_callbacks, fn {name, arity} ->
                  function_exported?(@contract_provider, name, arity)
                end)

              assert missing_callbacks == [],
                     "missing ReqLLM.Provider.Defaults callbacks: #{inspect(missing_callbacks)}"

              opts = [temperature: 0.2, provider_options: [contract_option: "value"]]

              model =
                LLMDB.Model.new!(%{provider: @contract_provider_id, id: "external-model"})

              assert {:ok, %Req.Request{method: :post} = request} =
                       @contract_provider.prepare_request(:chat, model, "Hello",
                         api_key: "test-key"
                       )

              assert request.url.path == "/chat/completions"
              assert request.options[:model] == "external-model"

              assert {^opts, []} = @contract_provider.translate_options(:chat, model, opts)

              usage = %{"prompt_tokens" => 4, "completion_tokens" => 2}
              assert {:ok, ^usage} = @contract_provider.extract_usage(%{"usage" => usage}, nil)

              assert [%ReqLLM.StreamChunk{type: :meta, metadata: %{terminal?: true}}] =
                       @contract_provider.decode_stream_event(%{data: "[DONE]"}, model)
            end
          end
        end
      )
    end
  end

  @doc false
  def required_provider_callbacks do
    callbacks = ReqLLM.Provider.behaviour_info(:callbacks)
    optional_callbacks = ReqLLM.Provider.behaviour_info(:optional_callbacks)
    callbacks -- optional_callbacks
  end

  @doc """
  Determines the environment variable key for a provider's API key.
  """
  def env_key_for(provider) do
    if function_exported?(provider, :default_env_key, 0) do
      provider.default_env_key()
    else
      provider_id = provider.provider_id()
      "#{provider_id |> Atom.to_string() |> String.upcase()}_API_KEY"
    end
  end

  @doc """
  Create a basic context fixture for testing.
  """
  def context_fixture do
    Context.new([
      Context.system("You are a helpful assistant."),
      Context.user("Hello, how are you?")
    ])
  end

  @doc """
  Create a model fixture from a model specification string.
  """
  def model_fixture(model_string) do
    {:ok, model} = ReqLLM.model(model_string)
    model
  end

  @doc """
  Create an OpenAI-format JSON response fixture.

  Compatible with OpenAI, Groq, and other OpenAI-compatible providers.
  """
  def openai_format_json_fixture(opts \\ []) do
    %{
      "id" => Keyword.get(opts, :id, "chatcmpl-test123"),
      "object" => "chat.completion",
      "created" => 1_234_567_890,
      "model" => Keyword.get(opts, :model, "llama-3.1-8b-instant"),
      "choices" => [
        %{
          "index" => 0,
          "message" => %{
            "role" => "assistant",
            "content" => Keyword.get(opts, :content, "Hello! I'm doing well, thank you.")
          },
          "finish_reason" => Keyword.get(opts, :finish_reason, "stop")
        }
      ],
      "usage" => %{
        "prompt_tokens" => Keyword.get(opts, :input_tokens, 10),
        "completion_tokens" => Keyword.get(opts, :output_tokens, 8),
        "total_tokens" => Keyword.get(opts, :total_tokens, 18)
      }
    }
  end

  @doc """
  Assert that a Response struct has the expected basic structure.
  """
  def assert_response_structure(%ReqLLM.Response{} = response) do
    assert is_binary(response.id)
    assert is_binary(response.model)
    assert %Context{} = response.context

    if response.usage do
      assert is_map(response.usage)

      for key <- [:input_tokens, :output_tokens, :total_tokens] do
        if Map.has_key?(response.usage, key) do
          assert is_integer(response.usage[key])
        end
      end
    end

    response
  end

  def assert_response_structure(other) do
    flunk("Expected %ReqLLM.Response{}, got: #{inspect(other)}")
  end

  @doc """
  Assert that response text content is present and valid.

  For tool call responses, text may be empty if tool calls are present.
  """
  def assert_text_content(%ReqLLM.Response{message: message} = response) do
    text = ReqLLM.Response.text(response)
    assert is_binary(text)

    has_tool_calls =
      message.content
      |> Enum.any?(fn part -> part.type == :tool_call end)

    if has_tool_calls do
      assert String.length(text) >= 0
    else
      assert String.length(text) > 0
    end

    response
  end

  @doc """
  Assert that JSON has no duplicate top-level keys.
  """
  def assert_no_duplicate_json_keys(json) when is_binary(json) do
    decoded = Jason.decode!(json, objects: :ordered_objects)

    keys =
      case decoded do
        %Jason.OrderedObject{values: values} -> Enum.map(values, fn {k, _} -> k end)
        map when is_map(map) -> Map.keys(map)
        _ -> []
      end

    duplicates =
      keys
      |> Enum.frequencies()
      |> Enum.filter(fn {_k, v} -> v > 1 end)
      |> Enum.map(fn {k, _} -> k end)

    assert duplicates == [], "Duplicate JSON keys: #{inspect(duplicates)}"

    json
  end

  @doc """
  Assert that a response has the expected basic structure and context merging.

  Verifies:
  - Response structure is valid
  - Text content is present  
  - Context advancement (original messages + new assistant message)
  """
  def assert_basic_response({:ok, %ReqLLM.Response{} = response}) do
    response
    |> assert_response_structure()
    |> assert_text_content()
    |> assert_context_advancement()
  end

  def assert_basic_response(other) do
    flunk("Expected {:ok, %ReqLLM.Response{}}, got: #{inspect(other)}")
  end

  @doc """
  Assert that the response context contains the original messages plus assistant response.
  """
  def assert_context_advancement(%ReqLLM.Response{context: context, message: message} = response)
      when not is_nil(message) do
    assert context.messages != []

    last_message = List.last(context.messages)
    assert last_message.role == :assistant
    assert last_message == message

    response
  end

  def assert_context_advancement(%ReqLLM.Response{} = response) do
    assert %Context{} = response.context
    response
  end

  @doc """
  Standard parameter bundles for consistent testing across providers.
  """
  def param_bundles(provider \\ :default) do
    base = %{
      deterministic: [
        temperature: 0.0,
        max_tokens: 50,
        seed: 42
      ],
      creative: [
        temperature: 0.9,
        max_tokens: 100,
        top_p: 0.8
      ],
      minimal: [
        temperature: 0.5,
        max_tokens: 50
      ]
    }

    case provider do
      :google ->
        %{
          deterministic: base.deterministic ++ [reasoning_token_budget: 0],
          creative: base.creative ++ [reasoning_token_budget: 0],
          minimal: base.minimal ++ [reasoning_token_budget: 0]
        }

      _ ->
        base
    end
  end
end
